language: c
addons:
  apt:
    packages: &1
    - lcov
# Compiler selection
compiler:
  - clang
  - gcc
script:
# Build steps
  - cmake -G "Unix Makefiles"
  - make -j 8
  - ctest -VV
after_success:
# Creating report
  - cmake -DENABLE_COVERAGE=ON
  - make
  - ctest -VV
  # Uploading report to CodeCov
  - bash <(curl -s https://codecov.io/bash)
