site_name: never-lang
site_author: Sławomir Maludziński
repo_url: https://github.com/never-lang/never
repo_name: GitHub
theme: readthedocs

nav:
   - Documentation: index.md
   - Tutorials:
       - Sorting - Quick Sort: qsort.md
       - Data Structures - Binary Tree: btree.md
       - Dynamic Programming - Rod Cutting : rodcut.md
       - Tribute to Alonso C.: curradd.md
       - Tail Recursion: tailrec.md
       - Neural Network: perceptron.md
       - Wave: wave.md
   - Contact: contact.md

